#!/usr/bin/env python3
"""Update test user passwords with correct Node.js generated hashes"""

import psycopg2

# Local Neon database (from docker-compose.dev.yml)
LOCAL_DB_CONFIG = {
    'host': 'ep-weathered-term-a5rmi9cx-pooler.us-east-2.aws.neon.tech',
    'database': 'neondb',
    'user': 'neondb_owner',
    'password': 'npg_foSr6ixkzw7W',
    'port': 5432
}

def main():
    try:
        print('🔐 Updating test user passwords with correct Node.js hashes...')
        
        # Connect to local database
        local_conn = psycopg2.connect(**LOCAL_DB_CONFIG)
        local_cursor = local_conn.cursor()
        
        print('✅ Connected to local Neon database')
        
        # Password hashes generated by Node.js script (matching auth.ts exactly)
        developer_hash = '105a6f92a57896b846f8c4a8b46e2ed113baf5fa3bb5d195c65ac56ae4ba5f08de7a445278f96e652dd2ff149df50636b25642d887fae680dfc02631dc910fd3.454c9a6c6261b6f9211b5d6ca09fec61'
        testuser_hash = '511d0e2f0570a08b961e74a546b03c7f7004273e3686966c4faa6406d7524fae3a615d5bead3acafc540eb6f83fd3642a9deb536b522937f9f3ff6283c712165.73d315b6debc41b64f883b485e387c99'
        
        # Update developer user
        print('👤 Updating developer user password...')
        local_cursor.execute(
            'UPDATE users SET password = %s, updated_at = NOW() WHERE username = %s',
            (developer_hash, 'developer')
        )
        developer_updated = local_cursor.rowcount
        
        # Update testuser user  
        print('👤 Updating testuser user password...')
        local_cursor.execute(
            'UPDATE users SET password = %s, updated_at = NOW() WHERE username = %s',
            (testuser_hash, 'testuser')
        )
        testuser_updated = local_cursor.rowcount
        
        # Commit the changes
        local_conn.commit()
        
        print(f'\n✅ Password updates completed!')
        print(f'   Developer user updated: {developer_updated > 0}')
        print(f'   Testuser user updated: {testuser_updated > 0}')
        
        # Verify the users exist and have the correct passwords
        local_cursor.execute('SELECT id, username, role, email FROM users WHERE username IN (%s, %s)', ('developer', 'testuser'))
        test_users = local_cursor.fetchall()
        
        print('\n👥 Updated test users:')
        for user in test_users:
            print(f'   ID: {user[0]}, Username: {user[1]}, Role: {user[2]}, Email: {user[3]}')
        
        local_cursor.close()
        local_conn.close()
        
        print('\n🎉 Ready to test authentication with correct password hashes!')
        print('🔐 Credentials:')
        print('   Username: developer, Password: admin123 (admin role)')
        print('   Username: testuser, Password: test123 (user role)')
        
    except Exception as e:
        print(f'❌ Error: {e}')
        return 1
    
    return 0

if __name__ == "__main__":
    exit(main()) 