UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 128;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 73;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 1;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 27;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 74;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 75;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 61;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 241;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 206;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 294;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 291;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 2;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 56;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 62;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 76;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 186;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 218;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 242;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 37;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 38;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 136;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 95;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 10;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 207;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 129;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 39;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 177;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 260;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 87;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 261;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 257;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 262;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 96;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 219;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 277;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 11;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 97;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 98;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 243;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 193;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 130;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 99;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 88;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 279;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 142;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 183;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 168;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 194;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 208;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 40;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 48;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 49;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 41;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 252;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 263;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 178;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 50;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 195;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 234;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 235;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 67;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 42;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 285;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 220;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 196;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 100;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 253;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 264;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 236;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 89;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 254;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 101;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 102;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 63;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 64;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 77;
UPDATE regulations SET responsible_office = 'Athletics', responsible_office_email = 'athletics@university.edu' WHERE id = 33;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 131;
UPDATE regulations SET responsible_office = 'International Programs', responsible_office_email = 'international@university.edu' WHERE id = 137;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 244;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 197;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 198;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 199;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 286;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 12;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 221;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 237;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 57;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 280;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 222;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 179;
UPDATE regulations SET responsible_office = 'Student Affairs', responsible_office_email = 'studentaffairs@university.edu' WHERE id = 295;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 223;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 292;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 289;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 180;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 181;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 224;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 103;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 13;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 281;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 174;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 265;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 282;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 14;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 238;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 245;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 212;
UPDATE regulations SET responsible_office = 'International Programs', responsible_office_email = 'international@university.edu' WHERE id = 138;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 266;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 213;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 182;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 225;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 267;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 65;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 79;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 226;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 104;
UPDATE regulations SET responsible_office = 'Health Services', responsible_office_email = 'healthservices@university.edu' WHERE id = 184;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 227;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 105;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 200;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 106;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 228;
UPDATE regulations SET responsible_office = 'Health Services', responsible_office_email = 'healthservices@university.edu' WHERE id = 189;
UPDATE regulations SET responsible_office = 'Health Services', responsible_office_email = 'healthservices@university.edu' WHERE id = 43;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 78;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 229;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 15;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 143;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 144;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 145;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 146;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 147;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 169;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 148;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 230;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 149;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 150;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 151;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 152;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 153;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 44;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 170;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 231;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 154;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 3;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 25;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 28;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 51;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 232;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 155;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 156;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 157;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 158;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 159;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 52;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 160;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 29;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 26;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 161;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 162;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 233;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 4;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 36;
UPDATE regulations SET responsible_office = 'Health Services', responsible_office_email = 'healthservices@university.edu' WHERE id = 185;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 201;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 5;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 202;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 214;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 132;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 215;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 107;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 80;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 239;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 192;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 268;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 269;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 171;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 175;
UPDATE regulations SET responsible_office = 'International Programs', responsible_office_email = 'international@university.edu' WHERE id = 139;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 140;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 9;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 355;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 203;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 53;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 66;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 81;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 216;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 108;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 90;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 109;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 190;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 110;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 278;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 246;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 247;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 204;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 47;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 255;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 270;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 111;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 112;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 113;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 114;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 115;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 116;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 117;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 118;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 119;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 120;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 121;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 287;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 122;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 133;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 91;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 58;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 299;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 300;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 303;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 304;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 309;
UPDATE regulations SET responsible_office = 'Legal / General Counsel', responsible_office_email = 'legal@university.edu' WHERE id = 311;
UPDATE regulations SET responsible_office = 'Athletics', responsible_office_email = 'athletics@university.edu' WHERE id = 316;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 320;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 305;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 307;
UPDATE regulations SET responsible_office = 'Information Technology', responsible_office_email = 'informationtechnology@university.edu' WHERE id = 315;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 318;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 308;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 314;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 301;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 310;
UPDATE regulations SET responsible_office = 'Legal / General Counsel', responsible_office_email = 'legal@university.edu' WHERE id = 313;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 312;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 319;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 306;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 317;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 321;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 322;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 323;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 324;
UPDATE regulations SET responsible_office = 'Registrar', responsible_office_email = 'registrar@university.edu' WHERE id = 325;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 326;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 327;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 328;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 329;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 330;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 331;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 332;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 333;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 334;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 335;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 336;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 337;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 338;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 339;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 340;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 341;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 342;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 343;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 344;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 345;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 346;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 347;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 348;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 349;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 350;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 351;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 352;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 353;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 354;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 298;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 297;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 302;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 296;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 172;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 173;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 217;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 72;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 248;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 271;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 249;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 256;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 272;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 283;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 16;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 163;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 273;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 176;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 17;
UPDATE regulations SET responsible_office = 'Compliance Office', responsible_office_email = 'compliance@university.edu' WHERE id = 288;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 284;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 274;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 123;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 124;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 250;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 134;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 135;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 18;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 6;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 30;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 34;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 59;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 82;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 187;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 19;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 45;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 275;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 251;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 54;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 20;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 125;
UPDATE regulations SET responsible_office = 'International Programs', responsible_office_email = 'international@university.edu' WHERE id = 191;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 164;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 165;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 21;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 166;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 55;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 205;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 60;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 68;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 126;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 92;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 35;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 7;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 31;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 69;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 83;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 93;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 167;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 188;
UPDATE regulations SET responsible_office = 'Campus Safety / Police', responsible_office_email = 'campussafety@university.edu' WHERE id = 258;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 293;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 290;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 8;
UPDATE regulations SET responsible_office = 'Admissions', responsible_office_email = 'admissions@university.edu' WHERE id = 32;
UPDATE regulations SET responsible_office = 'Disability Services', responsible_office_email = 'disabilityservices@university.edu' WHERE id = 70;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 84;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 259;
UPDATE regulations SET responsible_office = 'Environmental Health & Safety', responsible_office_email = 'environmentalhealth@university.edu' WHERE id = 127;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 46;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 209;
UPDATE regulations SET responsible_office = 'Research Compliance', responsible_office_email = 'researchcompliance@university.edu' WHERE id = 141;
UPDATE regulations SET responsible_office = 'Institutional Research', responsible_office_email = 'institutionalresearch@university.edu' WHERE id = 22;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 210;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 23;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 71;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 85;
UPDATE regulations SET responsible_office = 'Title IX Office', responsible_office_email = 'titleix@university.edu' WHERE id = 94;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 276;
UPDATE regulations SET responsible_office = 'Business Office / Finance', responsible_office_email = 'businessoffice@university.edu' WHERE id = 24;
UPDATE regulations SET responsible_office = 'Human Resources', responsible_office_email = 'humanresources@university.edu' WHERE id = 86;
UPDATE regulations SET responsible_office = 'Academic Affairs', responsible_office_email = 'academicaffairs@university.edu' WHERE id = 211;
UPDATE regulations SET responsible_office = 'Financial Aid Office', responsible_office_email = 'financialaid@university.edu' WHERE id = 240;