-- Export for table: regulation_versions
-- Exported on: 2025-05-29T18:37:07.502Z

-- Data for regulation_versions
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (4, 4896, 1, '{"name":"Davegulation 1: Campus Safety Standards","topic":"Campus Safety","requirements":"## Requirements\n\n- Implement emergency notification systems\n- Conduct safety drills quarterly\n- Appoint safety coordinators for each building\n\n## Compliance Deadlines\n\nInitial documentation: 6/1/2025\nFull implementation: 12/1/2025"}', '2025-01-15T05:00:00.000Z', 5, 'local', NULL, NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (5, 4896, 2, '{"name":"Davegulation 1: Campus Safety Standards","topic":"Campus Safety","requirements":"## Requirements\n\n- Implement emergency notification systems\n- Conduct safety drills quarterly\n- Appoint safety coordinators for each building\n- **NEW**: Develop evacuation plans for all buildings\n\n## Compliance Deadlines\n\nInitial documentation: 6/1/2025\nFull implementation: 12/1/2025"}', '2025-02-20T05:00:00.000Z', 5, 'mcp', 'MCP-V2-REG4896', NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (6, 4896, 3, '{"name":"Davegulation 1: Campus Safety Standards","topic":"Campus Safety","requirements":"## Requirements\n\n- Implement emergency notification systems\n- Conduct safety drills quarterly\n- Appoint safety coordinators for each building\n- Develop evacuation plans for all buildings\n- **NEW**: Install emergency communication stations\n\n## Compliance Deadlines\n\nInitial documentation: 6/1/2025\nFull implementation: 12/1/2025\n**UPDATED**: Final compliance review: 2/15/2026"}', '2025-03-10T04:00:00.000Z', 5, 'mcp', 'MCP-V3-REG4896', NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (7, 4897, 1, '{"name":"Davegulation 2: Data Privacy Protocol","topic":"Data Privacy","requirements":"## Requirements\n\n- Implement data encryption for all PII\n- Obtain explicit consent for data collection\n- Establish data retention policies\n\n## Compliance Deadlines\n\nInitial assessment: 5/15/2025\nFull compliance: 11/30/2025"}', '2025-02-10T05:00:00.000Z', 5, 'local', NULL, NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (8, 4897, 2, '{"name":"Davegulation 2: Data Privacy Protocol","topic":"Data Privacy","requirements":"## Requirements\n\n- Implement data encryption for all PII\n- Obtain explicit consent for data collection\n- Establish data retention policies\n- **NEW**: Conduct annual data privacy audit\n\n## Compliance Deadlines\n\nInitial assessment: 5/15/2025\nFull compliance: 11/30/2025"}', '2025-03-15T04:00:00.000Z', 5, 'mcp', 'MCP-V2-REG4897', NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (9, 4900, 1, '{"name":"Davegulation 5: Faculty Certification Requirements","topic":"Faculty Affairs","requirements":"## Requirements\n\n- Annual professional development hours\n- Subject matter expertise verification\n- Teaching methodology certification\n\n## Compliance Deadlines\n\nInitial certification: 9/1/2025\nFull faculty compliance: 3/15/2026"}', '2025-05-01T04:00:00.000Z', 5, 'local', NULL, NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (10, 4900, 2, '{"name":"Davegulation 5: Faculty Certification Requirements","topic":"Faculty Affairs","requirements":"## Requirements\n\n- Annual professional development hours (40 hours minimum)\n- Subject matter expertise verification\n- Teaching methodology certification\n- **NEW**: Diversity and inclusion training\n\n## Compliance Deadlines\n\nInitial certification: 9/1/2025\nFull faculty compliance: 3/15/2026"}', '2025-06-15T04:00:00.000Z', 5, 'local', 'LOCAL-EDIT', NULL);
INSERT INTO regulation_versions (id, regulation_id, version_number, content, created_at, created_by, source, source_id, validation_status) VALUES (11, 4900, 3, '{"name":"Davegulation 5: Faculty Certification Requirements","topic":"Faculty Affairs","requirements":"## Requirements\n\n- Annual professional development hours (40 hours minimum)\n- Subject matter expertise verification (renewed every 3 years)\n- Teaching methodology certification\n- Diversity and inclusion training (annual requirement)\n- **NEW**: Digital teaching competency assessment\n\n## Compliance Deadlines\n\nInitial certification: 9/1/2025\nFull faculty compliance: 3/15/2026\n**UPDATED**: Digital competency deadline: 6/30/2026"}', '2025-07-10T04:00:00.000Z', 5, 'mcp', 'MCP-V3-REG4900', NULL);

